#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ENV_FILE=/dev/null
REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)

banner "IN-CYPHER Rapido container setup"

stage "Docker and Linux target"
say "Only Docker, Buildx, Git, and this Bash/WSL2 shell are needed on the host."
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker is missing. Install Docker Engine or Docker Desktop, then rerun."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "Docker is not running or this shell cannot access its daemon."
  exit 1
fi
if ! docker buildx version >/dev/null 2>&1; then
  warn "Docker Buildx is unavailable. Enable the Buildx plugin, then rerun."
  exit 1
fi
docker buildx inspect --bootstrap >/dev/null
DOCKER_ARCH=$(docker info --format '{{.Architecture}}' 2>/dev/null || true)
case "$DOCKER_ARCH" in
  amd64|x86_64) DEFAULT_PLATFORM=linux/amd64 ;;
  arm64|aarch64) DEFAULT_PLATFORM=linux/arm64 ;;
  *) DEFAULT_PLATFORM=linux/amd64 ;;
esac
if [[ -z "${RAPIDO_PLATFORM:-}" ]]; then
  ask RAPIDO_PLATFORM "Linux target [${DEFAULT_PLATFORM}]:"
  RAPIDO_PLATFORM=${RAPIDO_PLATFORM:-$DEFAULT_PLATFORM}
fi
case "$RAPIDO_PLATFORM" in
  linux/amd64|linux/arm64) ;;
  *) warn "target must be linux/amd64 or linux/arm64"; exit 1 ;;
esac
if [[ -z "${RAPIDO_IMAGE:-}" ]]; then
  ask RAPIDO_IMAGE "Local image tag [rapido:local]:"
  RAPIDO_IMAGE=${RAPIDO_IMAGE:-rapido:local}
fi
note "selected $RAPIDO_PLATFORM as $RAPIDO_IMAGE"

stage "Private external state"
DEFAULT_SETUP_ROOT="${HOME}/.local/share/incypher-rapido"
if [[ -z "${RAPIDO_SETUP_ROOT:-}" ]]; then
  ask RAPIDO_SETUP_ROOT "Private setup root [${DEFAULT_SETUP_ROOT}]:"
  RAPIDO_SETUP_ROOT=${RAPIDO_SETUP_ROOT:-$DEFAULT_SETUP_ROOT}
fi
case "$RAPIDO_SETUP_ROOT" in
  \~) RAPIDO_SETUP_ROOT=$HOME ;;
  \~/*) RAPIDO_SETUP_ROOT="${HOME}/${RAPIDO_SETUP_ROOT#\~/}" ;;
esac
case "$RAPIDO_SETUP_ROOT" in
  /*) ;;
  *) warn "setup root must be an absolute Linux/macOS/WSL2 path"; exit 1 ;;
esac
case "/${RAPIDO_SETUP_ROOT#/}/" in
  *'/../'*|*'/./'*|*'//'*) warn "setup root must not contain ., .., or empty components"; exit 1 ;;
esac
while [[ "$RAPIDO_SETUP_ROOT" != / && "$RAPIDO_SETUP_ROOT" == */ ]]; do
  RAPIDO_SETUP_ROOT=${RAPIDO_SETUP_ROOT%/}
done
SETUP_ANCESTOR=$RAPIDO_SETUP_ROOT
SETUP_SUFFIX=""
while [[ ! -e "$SETUP_ANCESTOR" ]]; do
  SETUP_COMPONENT=${SETUP_ANCESTOR##*/}
  SETUP_SUFFIX="${SETUP_COMPONENT}${SETUP_SUFFIX:+/$SETUP_SUFFIX}"
  SETUP_ANCESTOR=${SETUP_ANCESTOR%/*}
  [[ -n "$SETUP_ANCESTOR" ]] || SETUP_ANCESTOR=/
done
if [[ ! -d "$SETUP_ANCESTOR" ]]; then
  warn "the nearest existing setup ancestor is not a directory"
  exit 1
fi
SETUP_ANCESTOR=$(cd -- "$SETUP_ANCESTOR" && pwd -P)
RAPIDO_SETUP_ROOT="${SETUP_ANCESTOR}${SETUP_SUFFIX:+/$SETUP_SUFFIX}"
case "$RAPIDO_SETUP_ROOT/" in
  "$REPO_ROOT/"*) warn "setup root must live outside the repository"; exit 1 ;;
esac
case "$REPO_ROOT/" in
  "$RAPIDO_SETUP_ROOT/"*) warn "setup root cannot contain the repository"; exit 1 ;;
esac
umask 077
mkdir -p "$RAPIDO_SETUP_ROOT"
STATE_DIR="$RAPIDO_SETUP_ROOT/state"
AUTH_DIR="$RAPIDO_SETUP_ROOT/codex-home"
ENV_FILE="$RAPIDO_SETUP_ROOT/rapido.env"
if [[ -L "$STATE_DIR" || -L "$AUTH_DIR" || -L "$ENV_FILE" ]]; then
  warn "state, auth, and env paths must not be symlinks"
  exit 1
fi
if [[ ! -e "$STATE_DIR" ]]; then mkdir "$STATE_DIR"; chmod 700 "$STATE_DIR"; fi
if [[ ! -e "$AUTH_DIR" ]]; then mkdir "$AUTH_DIR"; chmod 700 "$AUTH_DIR"; fi
touch "$ENV_FILE"
chmod 700 "$RAPIDO_SETUP_ROOT"
chmod 600 "$ENV_FILE"
note "state: $STATE_DIR"
note "native auth: $AUTH_DIR"
note "container env: $ENV_FILE"

stage "Dedicated Codex login"
say "The Docker build downloads pinned Codex for the selected target; no host Codex install is used."
LOGIN_IMAGE="rapido-setup-codex:${RAPIDO_PLATFORM#linux/}"
docker buildx build --platform "$RAPIDO_PLATFORM" --target codex --load \
  -t "$LOGIN_IMAGE" "$REPO_ROOT"
docker run --rm --platform "$RAPIDO_PLATFORM" --user 0 \
  --mount "type=bind,src=$AUTH_DIR,dst=/auth/codex" \
  --entrypoint sh "$LOGIN_IMAGE" -c \
  'chown -R 10001:10001 /auth/codex && chmod 700 /auth/codex'
if docker run --rm --platform "$RAPIDO_PLATFORM" --user 10001:10001 \
  --mount "type=bind,src=$AUTH_DIR,dst=/auth/codex" \
  --entrypoint sh "$LOGIN_IMAGE" -c 'test -f /auth/codex/auth.json' \
  && ! confirm "Refresh the existing dedicated Codex login?"; then
  note "keeping existing dedicated login"
else
  step "Follow the device-auth URL and code printed by Codex."
  DOCKER_INTERACTIVE=(-i)
  [[ -t 0 && -t 1 ]] && DOCKER_INTERACTIVE=(-it)
  docker run --rm "${DOCKER_INTERACTIVE[@]}" --platform "$RAPIDO_PLATFORM" \
    --user 10001:10001 -e CODEX_HOME=/auth/codex -e HOME=/auth/codex \
    --mount "type=bind,src=$AUTH_DIR,dst=/auth/codex" \
    --entrypoint codex "$LOGIN_IMAGE" login --device-auth
fi
docker run --rm --platform "$RAPIDO_PLATFORM" --user 0 \
  --mount "type=bind,src=$AUTH_DIR,dst=/auth/codex" \
  --entrypoint sh "$LOGIN_IMAGE" -c \
  'test -f /auth/codex/auth.json && chown -R 10001:10001 /auth/codex && chmod 700 /auth/codex && chmod 600 /auth/codex/auth.json'
note "dedicated native auth is ready and stays outside the repository"

stage "Board credentials and defaults"
say "Values are hidden and written only to the external mode-0600 container env file."
ask_secret CTFD_API_TOKEN "Paste CTFD_API_TOKEN:"
ask_secret TEAM_KEY "Paste TEAM_KEY:"
for SECRET_VALUE in "$CTFD_API_TOKEN" "$TEAM_KEY"; do
  if [[ -z "$SECRET_VALUE" || "$SECRET_VALUE" =~ [[:space:]] ]]; then
    warn "credentials must be non-empty and contain no whitespace"
    exit 1
  fi
done
write_env CTFD_URL "https://hackathon.in-cypher.com"
write_env CTFD_API_TOKEN "$CTFD_API_TOKEN"
write_env TEAM_KEY "$TEAM_KEY"
write_env RAPIDO_CODEX_HOME "/auth/codex"
write_env RAPIDO_STATE_PATH "/state/rapido.sqlite3"
write_env RAPIDO_WORK_ROOT "/state/work"
write_env RAPIDO_CODEX_BINARY "codex"
write_env RAPIDO_MODEL "gpt-daybreak-blue-latest"
write_env RAPIDO_REASONING_EFFORT "xhigh"
write_env RAPIDO_SPECIALIST_MODEL "gpt-5.6-luna"
write_env RAPIDO_SPECIALIST_REASONING_EFFORTS "max,xhigh,max"
write_env RAPIDO_LEAD_LANES "2"
write_env RAPIDO_PEER_PROFILE "mixed_v1"
write_env RAPIDO_MEMORY_ARM "typed_challenge_v1"
write_env RAPIDO_CONCURRENCY "20"
write_env RAPIDO_ACTIVE_CHALLENGES "5"
write_env RAPIDO_ATTEMPTS_PER_CHALLENGE "4"
write_env RAPIDO_EPISODES_PER_CHALLENGE "3"
write_env RAPIDO_ATTEMPT_SECONDS "800"
write_env RAPIDO_BOARD_TIMEOUT_SECONDS "15"
write_env RAPIDO_INSTANCE_READY_SECONDS "120"
write_env RAPIDO_INSTANCE_CLEANUP_SECONDS "45"
write_env RAPIDO_DYNAMIC_CONCURRENCY "1"
write_env RAPIDO_SUBMIT_CANDIDATES "true"
write_env RAPIDO_MANAGE_DYNAMIC_INSTANCES "true"
chmod 600 "$ENV_FILE"

stage "Build and smoke test"
say "The final image downloads and installs Rapido, pinned Codex, and every current native inspection tool."
docker buildx build --platform "$RAPIDO_PLATFORM" --load -t "$RAPIDO_IMAGE" "$REPO_ROOT"
docker run --rm --platform "$RAPIDO_PLATFORM" --user 0 \
  --mount "type=bind,src=$STATE_DIR,dst=/state" \
  --mount "type=bind,src=$AUTH_DIR,dst=/auth/codex" \
  --entrypoint sh "$RAPIDO_IMAGE" -c \
  'install -d -o 10001 -g 10001 -m 0700 /state/work && chown 10001:10001 /state /auth/codex /auth/codex/auth.json && chmod 700 /state /auth/codex && chmod 600 /auth/codex/auth.json'
docker run --rm --platform "$RAPIDO_PLATFORM" --entrypoint codex "$RAPIDO_IMAGE" --version
docker run --rm --platform "$RAPIDO_PLATFORM" --env-file "$ENV_FILE" \
  --entrypoint rapido "$RAPIDO_IMAGE" config | python3 -c '
import json, sys
value = json.load(sys.stdin)
assert value["active_challenges"] == 5
assert value["attempts_per_challenge"] == 4
assert value["concurrency"] == 20
assert value["model"] == "gpt-daybreak-blue-latest"
assert value["specialist_model"] == "gpt-5.6-luna"
assert value["specialist_reasoning_efforts"] == ["max", "xhigh", "max"]
assert value["memory_arm"] == "typed_challenge_v1"
'
note "image and architecture smoke tests passed"

stage "Read-only Board preflight"
say "This authenticates to the Board and reads its catalogue. It does not start Codex, submit, or manage instances."
COMMON_RUN=(
  docker run --platform "$RAPIDO_PLATFORM" --stop-timeout=190 --read-only
  --cpus=8 --memory=24g --pids-limit=256 --cap-drop=ALL
  --security-opt=no-new-privileges:true --env-file="$ENV_FILE"
  --mount "type=bind,src=$STATE_DIR,dst=/state"
  --mount "type=bind,src=$AUTH_DIR,dst=/auth/codex"
  --tmpfs "/tmp:rw,noexec,nosuid,nodev"
)
"${COMMON_RUN[@]}" --rm --entrypoint rapido "$RAPIDO_IMAGE" preflight
printf '\n  %sLive run command (not started):%s\n  ' "$BOLD" "$RESET"
printf '%q ' "${COMMON_RUN[@]}" --detach --restart unless-stopped --name rapido "$RAPIDO_IMAGE"
printf '\n\n'
note "Keep that command unattended. Stop with: docker stop --time 190 rapido"

finish
